### ISSUE TITLE
Pokemon Example BUG!

### ISSUE THREAD

**Issue by reinvdv** [MediacollegeAmsterdam/tour#24]
Bij de pokemon tour is er een bug bij een bepaalde plek dat als je wilt oversteken van de straat kan dat niet met foward maar moet je backward gebruiken...

de plek van de bug:
rechtrij 2de bolletje van boven 
dan naar links dat doet het niet

http://snoh.hosts.ma-cloud.nl/projects/tour/prototypeTour/tour10.html

**Comment by JessedeJong** [comment]
Not relevant anymore
