### ISSUE TITLE
Firefox versie 55.0.3 css viewer onbruikbaar

### ISSUE THREAD

**Issue by Joshuavtk** [MediacollegeAmsterdam/tour#25]
Klikken en slepen doen beide niks.
Console errors:
```
Onverwachte waarde NaN bij parsen van y1-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van y2-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van y1-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van y2-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van x1-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van x2-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van x1-attribuut.  markup.js:335:6
Onverwachte waarde NaN bij parsen van x2-attribuut.  markup.js:335:6
```
markup.js:335:6 bevat: 
```
this.content.setAttributeForElement(id, name, value);
```

**Comment by beauterre** [comment]
markup.js is geen deel van de library. y1 en x1 volgens mij ook niet.
Gezien bij Jesse.
Zelf oude versie getest, http://snoh.hosts.ma-cloud.nl/projects/tour/protoytpe360_viewer/index2.html
probleem is er bij mij ook, (hele oude browser) 
nieuwe versie firefox geinstalleerd. straks nog eens proberen.: 
Dit probleem is wEG in de nieuwe firefox, echter mouseEvent afhandeling gaat mis.

**Comment by ghost** [comment]
AddEventListener on firefox does nothing

**Comment by JessedeJong** [comment]
After update, problem seems solved.

**Comment by beauterre** [comment]
Nice! Guys.. Thanks.
