### ISSUE TITLE
View been fucked up

### ISSUE THREAD

**Issue by StefvanEgmond** [MediacollegeAmsterdam/tour#37]
![screenshot_3](https://user-images.githubusercontent.com/23499242/30687810-b53c4980-9ebc-11e7-8dbb-414a06a628b4.png)
De view is *** up

Browser: Chrome 61
OS: Windows 10 1709
Res: 1920 x  1080

**Comment by JRoodenburg** [comment]
Lijkt mij een client side issue, 
Browser: Chrome 60
OS: Windows 10 1607
Res: 1920 x 1080

Ik zet hem neer als bug voor verdere bugtests

![image](https://user-images.githubusercontent.com/21284189/30689232-a39f3364-9ec0-11e7-8457-d2ec91c853d6.png)

**Comment by StefvanEgmond** [comment]
Je moet panorama aan zetten en dan naar boven of beneden schuiven

**Comment by JRoodenburg** [comment]
Zie nu het probleem inderdaad, bedankt voor de issue

**Comment by beauterre** [comment]
Ik vrees dat dit gewoon een artefact is van de skybox.. als we dat moeten fixen, moeten we naar een GLSL sphere map. Iets lastiger.. Maar ook te doen :)

**Comment by beauterre** [comment]
Overigens denk ik, dat het met de nieuwe versie PanoSphere beter is???

**Comment by JRoodenburg** [comment]
Bug / issue is er nog steeds in de nieuwe versie
![image](https://user-images.githubusercontent.com/21284189/30702452-45edd1da-9eed-11e7-9f30-7efbd5a424f7.png)


@HjalmarSnoep  , zouden we geen 3D camera gebruiken?? (die zou naar school komen/geleend worden zover ik had begrepen?)

**Comment by beauterre** [comment]
Klopt, helaas heeft de afdeling VR ons laten zitten, vonden het achteraf toch te kort dag. Jammer, want een week geleden was het nog geen probleem. Zou er woensdag zijn. Excuses. Had ik even moeten noemen. Dit is geen BUG. Het heeft te maken met de Skybox. Het is een illusie van 3D.
Om dit te veranderen moet je naar Equirectangular 3D.

**Comment by beauterre** [comment]
https://www.sitepoint.com/building-a-full-sphere-3d-image-gallery-with-react-vr/

Dit is het alternatief, via GLSL. Ik zou echter de tijd willen nemen om een beter alternatief te schrijven door een eigen fragment shader te maken.
Equirectangular projectie vernaggelt de vloer en er is geen reden waarom we niet direct van de cube-map zouden werken. Deze zijn ook makkelijker te editen in Photoshop..
Dus ik ga dit issue CLOSEN, met wontfix
Je mag een poging doen, als je wilt, maar anders dan (misschien) three.js wil ik geen andere dependencies introduceren, het moet een beginners project blijven.
