### ISSUE TITLE
image clicking doesn't work in chrome

### ISSUE THREAD

**Issue by KevinStreekstra** [MediacollegeAmsterdam/tour#56]
can't click on the images.

**Comment by bassapguy** [comment]
it is working

**Comment by JessedeJong** [comment]
It is working, update your browser

**Comment by beauterre** [comment]
En dit is waarom we een overzicht nodig hebben van welke browser werkt, deze issue is dus waardevol, liever niet sluiten, totdat we hem verwerken in een tabelletje.
Kevin, Welke browser versie, systeem, bijvoorbeeld ff55 op windows 8

**Comment by Dalimk** [comment]
https://github.com/MediacollegeAmsterdam/tour/wiki/Compitability
In de wiki staat een klein overzicht, mocht die er niet bijstaan kan je hieronder testen of jou browser het doet!
https://github.com/MediacollegeAmsterdam/tour/issues/48
