### ISSUE TITLE
Safari Problems

### ISSUE THREAD

**Issue by ghost** [MediacollegeAmsterdam/tour#7]
Bij het rondkijken doet ie raar
Het beeld glitched bij het rondkijken

http://snoh.hosts.ma-cloud.nl/projects/tour/protoytpe360_viewer/index3.html

probleem is waarschijnlijk in: 
Zie: https://css-tricks.com/almanac/properties/b/backface-visibility/

**Comment by beauterre** [comment]
Welke versies van Safari WEL en NIET?
Welk OS en versie, kunnen we daar een consistentie in ontdekken, dan kan hij naar de safari developerds :)

**Comment by ghost** [comment]
Ik heb het getest op Safari 10.1.2
Dit op een MacBook Pro Retina late 2015 met MacOS Sierra 10.12

Ook in de laatste Safari Developers build geeft hij problemen.

**Comment by ghost** [comment]
Fixed by adding vendor prefix for Safari (webkit)
